/*
 * This source file was generated by the Gradle 'init' task
 */

package org.example;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.ApplicationContext;

@SpringBootTest
class AppTest {
    @Autowired
    ApplicationContext applicationContext;

    @Test
    void appHasAGreeting() {
        Assertions.assertNotNull("app", applicationContext.getApplicationName());
    }
}
